# Generated by Django 4.2.3 on 2023-07-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoterList',
            fields=[
                ('firstname', models.TextField(max_length=225)),
                ('secondname', models.TextField(max_length=225)),
                ('rno', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
