# Generated by Django 4.2.3 on 2023-07-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlist',
            name='firstname',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='voterlist',
            name='secondname',
            field=models.CharField(max_length=225),
        ),
    ]
