# Generated by Django 4.2.3 on 2023-07-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_alter_voterlist_firstname_alter_voterlist_secondname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterlist',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='voterlist',
            name='secondname',
        ),
        migrations.AddField(
            model_name='voterlist',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
