# Generated by Django 4.2.3 on 2023-07-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_voterlist_dept_voterlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterlist',
            name='voter_image',
            field=models.ImageField(default='default.jpg', upload_to='voter_pics/'),
        ),
        migrations.AlterField(
            model_name='voterlist',
            name='dept',
            field=models.CharField(blank=True, choices=[('it', 'information technology'), ('cse', 'computer scienccce')], max_length=50, null=True),
        ),
    ]
