# Generated by Django 4.2.3 on 2023-07-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('rno', models.TextField(max_length=10, unique=True)),
                ('blood_grp', models.TextField(max_length=5)),
            ],
        ),
    ]
