# Generated by Django 5.0.9 on 2024-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('second_name', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50, null=True)),
                ('department', models.CharField(choices=[('Information Technology', 'Information Technology')], max_length=50, null=True)),
                ('rno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('photo', models.ImageField(default='default.jpg', upload_to='candidate_pics/')),
                ('votes', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
