# Generated by Django 4.2.3 on 2023-07-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatereg', '0002_remove_candidates_blood_grp_remove_candidates_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='department',
            field=models.CharField(choices=[('it', 'information technology'), ('cse', 'computer scienccce')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50, null=True),
        ),
    ]
