# Generated by Django 4.2.3 on 2023-07-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatereg', '0004_candidates_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='department',
            field=models.CharField(choices=[('Information Technology', 'Information Technology')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
